### ISSUE TITLE
no AuthProvider named DEVOPS_CENTER_GITHUB found

### ISSUE THREAD

**Issue by Peteris-Visma** [forcedotcom/devops-center-feedback#122]
**To Reproduce**
1. Install DevOps Center in Sandbox.
2. Recieve the error that installation failed.

`1. (DevOps_Center_GitHub) In field: authProvider - no AuthProvider named DEVOPS_CENTER_GITHUB found
DevOps_Center_GitHub: In field: authProvider - no AuthProvider named DEVOPS_CENTER_GITHUB found`

If I create Auth provider manually with the name DEVOPS_CENTER_GITHUB, installation is successful. I can connect to Github, create a new work item, and pull the changes. But when I am trying to commit the changes I get an "Out of Bounds" error.

I already tied to reinstall the package but it seems that I can not get out of this failure loop.

**Comment by matteomini** [comment]
Hi @kfidelak94, I ran into the same issue. Could you please re-enable also my org?

The OrgId is: 00D1t000000DuVe

**Comment by geomuck** [comment]
Hi @matteomini : did you by chance follow the uninstallation instructions? I ask because I'm not seeing the Auth Providers in your org at all, even though the DevOps Center preference is enabled. If you've deleted the Auth Providers manually yourself, that's fine, and @kfidelak94 can help to get them re-created. If not, I'd like to investigate further in to what happened where they weren't created for you automatically.

Thank you!

**Comment by geomuck** [comment]
Perfect, thank you for confirming! We'll get you fixed up here shortly.

**Comment by geomuck** [comment]
OK @matteomini , you should be all set now. Please try again at your convenience?

**Comment by matteomini** [comment]
Yes, it works properly now!! 

Many thanks @geomuck @kfidelak94
