### ISSUE TITLE
Delete Project

### ISSUE THREAD

**Issue by johp-lb-dk** [forcedotcom/devops-center-feedback#130]
Ability to delete a not used project.

**Comment by dnascimento** [comment]
Is there a workaround ?

**Comment by kfidelak94** [comment]
@dnascimento The current workaround for this is to rename the project (via a Lightning record page - let me know if you need more info on how to do this) - this allows you to indicate the project is obsolete and also get it to appear at the bottom of the list.  This at least lets folks know that the project shouldn't be used, and also helps with the clutter it can cause in the list.  In the next release we will provide a way within DevOps Center to rename it, so you don't have to do it via standard Lightning record pages.  In a subsequent release we'll be looking at providing a way to "Hide" or "Deactivate" the project to get it out of the list view altogether.  From our understanding the primary desire for what people are calling "Delete" is really to get it out of the list view.  Please confirm if that would meet your needs as well.  Actual "Delete" is a harder thing to accomplish due to related objects in the data model.  So if we can meet your needs with a more simple "Hide" or "Deactivate", that is what we'd prefer to do.

**Comment by kfidelak94** [comment]
This is also covered in https://github.com/forcedotcom/devops-center-feedback/issues/69
