### ISSUE TITLE
Is it possble to deploy a ExperienceBundle with DevOpsCenter?

### ISSUE THREAD

**Issue by johp-lb-dk** [forcedotcom/devops-center-feedback#146]
Is it possble to deploy a ExperienceBundle with DevOpsCenter?

**Comment by Schuchie** [comment]
Expierence bundles are often used with navigation variations, the use of which is not currently supported. Audiences for the navigation variations are also needed. Whereby a standard Audience sometimes triggers errors, since Scratch Orgs require at least filtering in the Audiences and Sandbox only accepts default Audiences without filtering.
