### ISSUE TITLE
Ending position out of bounds: -1

### ISSUE THREAD

**Issue by Peteris-Visma** [forcedotcom/devops-center-feedback#158]
**Describe the bug**
When committing changes from Development Environment to Source Control Branch error is shown: "Ending position out of bounds: -1"

**To Reproduce**
1. Create a work item
2. Pull changes from Development Environment - in this case, I created a new class
3. Commit it to Source Control Branch WI-000001 (the branch is available on GitHub)
4. Get out of bounds error
![error_image_out_of_bounds](https://user-images.githubusercontent.com/78899781/165235967-5d82aeef-2706-46a8-9209-efbe9269047d.PNG)

**Comment by TCEmpaua** [comment]
Is there an update on this?

**Comment by renatoliveira** [comment]
Just had this issue happen to me.

Installed DevOps Center in a production instance. Had a source tracking-enabled sandbox already in place before this environment was created. 

Both environments were named after the company's name, like `Company_Prod` and `Company (srctrack)` for the production and sandbox respectively.

Created a new pipeline with just the two.

Proceeded to create a new work item, tried to add four classes to it. Pulling for changes work, but when trying to commit I get the same out of bounds error message.

Error happens with all possible scenarios: adding one class, two classes or the four classes from the list of changes.

Note: when opting for selecting the changes manually ("Add Changes Manually") my Firefox tab freezes due to the amount of items, so this option is an issue for large code bases. Please consider using pagination or improve the data table rendering, haha. Also: the classes are not added to the work item's commit. :sweat_smile: 

If you want some environments to repro this issue, @andresrivas-sf, you can find it with the environment 00D5E000000AAfcUAG and its production instance.

**Comment by franciscoperezsammartino** [comment]
Hi, we have this Work Item W-11072209 related to this issue. As soon as we have any update we will come back and post it here, sorry for the delay and troubles this might cause.

Related to the pagination issue, thanks for the feedback and we do have plans to fix that in future releases.

**Comment by kfidelak94** [comment]
This error is generally an exception that we're throwing as a result of some other underlying error.  In the upcoming GA release, planned to release in December, we'll have a fix to allow that underlying error to be logged and displayed instead of this generic exception.

**Comment by A424162** [comment]
I have updated to the latest version of DevOps Center and I still receive this generic messaging.  
**_"Ending position out of bounds: -1"_**

**Comment by rickroesler** [comment]
@kfidelak94 @geomuck We've updated the Elements production org to 5.3.0 GA release. I re-tested and am still getting the error. There is no additional information that I can see.

![image](https://user-images.githubusercontent.com/19243272/208501977-692e0b97-86d7-4bc6-9500-4d1f25512dbd.png)

**Comment by amaruji** [comment]
I'm having this issue as well, despite it appearing the bug was supposed to be fixed in December. Has anyone been able to find a workaround?

**Comment by rickroesler** [comment]
@amaruji I've opened a case with Salesforce. They're actively trying to understand and fix the issue in our org.

**Comment by A424162** [comment]
@rickroesler I did this same (In January).  They said a patch would be implemented in mid February.  I am still encountering the issue and have opened a case again.  No response yet.

**Comment by franciscoperezsammartino** [comment]
Hi,
we are aware of several reports regarding the same issue, and are working on a fix for this to be released on following releases. Sorry for this.

**Comment by orestskoropadform** [comment]
Hi Team
I'm facing exactly the same error. 2/22/2023. Cool Idea but it doesn't work :-(
Thank you

**Comment by orestskoropadform** [comment]
I found the article and it helps to solve the problem for other app(please see link below)
https://support.veeva.com/hc/en-us/articles/360046255494-Error-Ending-position-out-of-bounds-1-When-Using-Edit-DCR-button-in-Veeva-CRM-Lightning

**Comment by rickroesler** [comment]
@orestskoropadform I've added your comment to my open case with Salesforce support.

**Comment by orestskoropadform** [comment]
> 

I've added the same to my case. Support says that it would be better to wait for a new version.
