### ISSUE TITLE
Sometimes external commits take a VERY long time to update DevOps Center

### ISSUE THREAD

**Issue by rickroesler** [forcedotcom/devops-center-feedback#191]
**Describe the bug**
When you make external commits directly to GitHub (eg, from VS Code), sometimes DevOps Center gets updated almost immediately. Sometimes it takes a long time (an example where the delay was over an hour is below). What should our expectation be for this?

**To Reproduce**
Behavior is intermittent and not reproducible.

**Expected behavior**
DevOps Center is always updated within xx minutes of an external commit.

**Screenshots**
In this example, the commit was done at 10:54am and DevOps Center was updated at 12:03pm

![image](https://user-images.githubusercontent.com/19243272/176759018-82e0d886-24be-4052-94af-90ad0a497293.png)

**Comment by kfidelak94** [comment]
Hi @rickroesler Yes, we've been seeing this kind of very variable (and sometimes very long) response time here as well.  It's due to the response time of the event coming from GitHub.  We're working with GitHub to understand this better in terms of response time expectation and optimal implementation.  We've seen a degradation in the performance here fairly recently.  It does appear to be affected (and GitHub has confirmed to us) by peak/off-peak times, FWIW.

**Comment by pkozuchowskiPS** [comment]
Hmm - not sure if this is the same issue, but when I comitted and pushed my commits from git, I couldn't change the work item to Review status - Button was grayed out and activity tab was empty. 
This "validation" on button may bring more harm than good. If it were enabled all the time while In Progress status, worst that could happen would be empty PR, but right now it has potential to block workflow.

**Comment by franciscoperezsammartino** [comment]
Hi @pkozuchowskiPS , thanks for the comment. Just to confirm we are understanding correctly, you followed these steps:
1. Commit Externally into Work Item's feature branch(not using DevOps Center)
2. Tried to Create Review from the Work Item in DevOps Center. (before the commit event to arrive)
Cannot do (2) because the button is disabled.

You are right, we have this validation in place that verifies if there has been some commit on the Work Item. And right now this depends on the event to come.

We will consider this in the following releases. One workaround now would be to make any commit (something minor) from DevOps Center and that will instantly allow you to create the review.

Thanks again.

**Comment by pkozuchowskiPS** [comment]
Hi @franciscoperezsammartino You are correct in your understanding and actually the mentioned workaround is exactly what I did.

Kind Regards

**Comment by RupertBarrow** [comment]
I have the same issue.

I presume this feature is based on a Github webhook or action.
Could you possibly add a "Refresh GitHub activity" button in the Activity History tab, to ask DevOps to pull those changes in from GitHub - just for frustated devs who are deploying their own changes and don't want to wait ?

Moreover, this is a blocker in demos to other devs and is NOT good for devs adoption.

**Comment by franciscoperezsammartino** [comment]
Hi Rupert,

For the last part, yes. Dev Ops Center will be querying github for new
events as long as the app is running. If you close the app this process
will be stopped until it is opened again. This is what causes the batches
that you are seeing.

Also, we are experiencing some delays that might get to hours on github
posting the events, so it is not a problem of querying more frequently but
to github to post the event.

That said we are working on making this flow better and avoid long delays.

Thanks !

**Comment by kfidelak94** [comment]
GitHub events performance returned to acceptable speeds and we haven't been seeing these kinds of delays for a few months.  Please comment if this crops up again.

**Comment by msouther-lisc** [comment]
I have been waiting 20+ minutes for my direct commits to show up, which is not as bad as some have reported, but still not good for my workflow.

I'm inferring that Salesforce is relying on the GitHub Events API behind the scenes, and there are some known performance issues with this API that can come up intermittently. I'd like to echo @RupertBarrow 's request for something like a "Refresh GitHub activity" button that might instead use the GitHub REST API behind the scenes to check for activity on a specific branch, rather than relying entirely on a fickle event-based API.

**Comment by mmh7181** [comment]
Came upon this issue looking for some answers, it seems there is no solution in sight. Waited for 37 minutes for the commit to show in DevOps Center, and then 7 hours for the PR to be applied and the WorkItem to move  In Progress to In Review.

**Comment by ahrensjosephPFG** [comment]
My team is also experiencing these issues, sometimes up to an hour or even more wait times just to get the external commits so we can make the PRs.

**Comment by JeremieNabet** [comment]
Two years after the initial comment, we are still waiting for the new button. When will this be implemented?
I had to wait until the next day to see the 'Create Review' button available...

**Comment by adjohnson-frs** [comment]
echoing the sentiment of inhibiting dev adoption. experiencing the same issue on my team, now in 2024 - 

1. create the WI via Devops
2. select that you would like to manage externally, creating the branch
3. make changes to dev branch in IDE
4. PR/merge dev branch with integration branch
5. wait (we are at 1.5 hours), with 0 indication of whether or not we need to take action. referring to documentation, which just states, "delays can occur between when these actions happen and when they’re reflected in DevOps Center"

should this issue actually be in a closed state?

**Comment by vladimirsavenkov** [comment]
I second the people above. For the last 3 months for us this behavior (wait for external commits to appear in devops center) is rather a rule than an exception. 

I do get that sometimes GH events might be delayed, but we'd be more than happy to have a button to basically "Pull from GH". 

PS: BTW, we do not see this behaviour https://github.com/forcedotcom/devops-center-feedback/issues/191#issuecomment-1183110701 Or at least it is not visible. One must wait for tens of minutes/hours to see external commits.

**Comment by mmh7181** [comment]
It seems this is actively being worked on under a different issue and is already included in the [roadmap](https://github.com/orgs/forcedotcom/projects/4/views/1?pane=issue&itemId=24383308), posting here for reference.

[Updates made directly in GitHub should be more reliably reflected in DevOps Center](https://github.com/forcedotcom/devops-center-roadmap/issues/96)
